Source path: src/simple.test.clunk
import stdlib/assertions.assertThat;
import stdlib/matchers.equalTo;

test "assert False" {
    assertThat(false, equalTo(true));
}

test "assert True" {
    assertThat(true, equalTo(false));
}

test "assert 42 == 47" {
    assertThat(42, equalTo(47));
}

test "assert 42 == 42" {
    assertThat(42, equalTo(42));
}


==============

Output path: simple_test.py
from __future__ import annotations

from precisely import assert_that
from precisely import equal_to

def test_assert_false():
    assert_that(False, equal_to(True))

def test_assert_true():
    assert_that(True, equal_to(False))

def test_assert_42_equals_47():
    assert_that(42, equal_to(47))

def test_assert_42_equals_42():
    assert_that(42, equal_to(42))


==============

============================= test session starts ==============================
rootdir: ROOTDIR, configfile: tox.ini
collected 4 items

simple_test.py FFF.                                                      [100%]

=================================== FAILURES ===================================
______________________________ test_assert_false _______________________________
simple_test.py:7: in test_assert_false
    assert_that(False, equal_to(True))
SITE-PACKAGES/precisely/__init__.py:50: in assert_that
    raise AssertionError("\nExpected:{0}\nbut:{1}".format(
E   AssertionError: 
E   Expected:
E     True
E   but:
E     was False
_______________________________ test_assert_true _______________________________
simple_test.py:10: in test_assert_true
    assert_that(True, equal_to(False))
SITE-PACKAGES/precisely/__init__.py:50: in assert_that
    raise AssertionError("\nExpected:{0}\nbut:{1}".format(
E   AssertionError: 
E   Expected:
E     False
E   but:
E     was True
___________________________ test_assert_42_equals_47 ___________________________
simple_test.py:13: in test_assert_42_equals_47
    assert_that(42, equal_to(47))
SITE-PACKAGES/precisely/__init__.py:50: in assert_that
    raise AssertionError("\nExpected:{0}\nbut:{1}".format(
E   AssertionError: 
E   Expected:
E     47
E   but:
E     was 42
=========================== short test summary info ============================
FAILED simple_test.py::test_assert_false - AssertionError: 
FAILED simple_test.py::test_assert_true - AssertionError: 
FAILED simple_test.py::test_assert_42_equals_47 - AssertionError: 
========================= 3 failed, 1 passed in TIME ==========================